server=http://localhost:4111
apiVersion=/api/v1/
api.contractVersion=with_database

admin.username=admin
admin.password=admin

db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres

uiRemote=http://localhost:4444/wd/hub
uiBaseUrl=http://host.docker.internal:3000
browser=chrome
browserVersion=128.0
browserSize=1920x1080
