CreateUserRequest=CreateUserResponse:username=username,role=role
DepositRequest=DepositResponse:id=id,balance=balance
DepositTransferRequest=DepositTransferResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount
FraudTransferResponse=FraudTransferResponse:status=status,message=message,transactionId=transactionId,senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount,fraudRiskScore=fraudRiskScore,fraudReason=fraudReason,requiresManualReview=requiresManualReview,requiresVerification=requiresVerification
