CreateUserRequest=CreateUserResponse:username=username,role=role
DepositRequest=DepositResponse:id=id,balance=balance
DepositTransferRequest=DepositTransferResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount
